### ISSUE TITLE
Text fields not working in web container, works with href

### ISSUE THREAD

**Issue by digeratus** [Jasonette/JASONETTE-iOS#210] opened 2017-06-14 21:55 UTC
I have a very simple form with three fields embedded in a web container. For some reason, the first text field accepts text entry, but not on the second or third. If one submits multiple times one of the remaining fields might accept input. The funny thing is that the erratic behavior only occurs as a web container, it works as a view:href. 

Here’s the jason file to test and debug:
https://www.jasonbase.com/things/1jQK.json

**Comment by gliechtenstein** [comment] 2017-06-15 18:54
This is probably because of the remote `iframe` being used in the markup.

Two ways to solve this problem:

1. Recommended: Don't use web container for these things. Jasonette is NOT a way to just embed websites into a native looking shell. You can use phonegap https://phonegap.com/ for that. If you have access to their REST API, you should use those instead via `$network.request`.
2. If you really must use web view: Generally, iframes are buggy, especially the iframes being remotely loaded. If you really must use the web interface, try using a fully local HTML markup. For example instead of the `<iframe src>` use a full HTML markup for all the forms, etc. 

I think the web container is causing confusion for some people. The best way to think about it is: it's just another component like `label`, `image`, `slider`, etc. You should be using it as a way to display rich content, but not as a way to replace native app. For example, it can display rich dynamic content like charts, animations, etc., and you are encouraged to use web containers for those purposes, but NOT for forms (you should use the native `textfield`, `textarea`, etc. for it), and NOT for navigation (If your first view is a web view, the only way to navigate away is via HTML links, which means you will end up with your entire app being nothing more than a bunch of websites embedded in a "native" shell).  Lastly, you should always hardcode HTML directly in the JSON markup as much as you can when using web containers. Loading them remotely via something like `iframe src` just adds another layer of potential bugginess.

Anyway, I did take a quick look to see if I can quickly fix this. But the problem is pretty tricky to solve because it's an inherent problem with how `UIWebView` (which the web container uses) handles iframes. Furthermore, this bug only happens when you use Jasonette in ways that are not recommended.

For these reasons, I will just mark this as "won't fix" and move on. Hope my tips above can get you through this.

**Closed as completed by gliechtenstein** 2017-06-15 18:54 UTC
Labels: wontfix

**Comment by digeratus** [comment] 2017-06-15 23:10
Makes sense. Perhaps adding notes to the documentation- if it isn’t there already - would make sense to inform others on proper use and limitations as is the case for iframes. Thanks
